name: Update Last Updated Timestamp

on:
  push:
    branches: 
      - main

permissions:
  contents: write

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Skip if commit was made by GitHub Actions itself
        run: |
          if [[ "$(git log -1 --pretty=%an)" == "github-actions[bot]" ]]; then
            echo "Commit made by bot â†’ Skipping."
            exit 0
          fi

      - name: Set IST timezone
        run: |
          sudo timedatectl set-timezone Asia/Kolkata
        shell: bash

      - name: Generate formatted date
        id: date_step
        run: |
          echo "TIMESTAMP=$(date +"%B %d, %Y - %I:%M %p IST")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Write timestamp to file
        run: |
          mkdir -p variables
          echo "${{ steps.date_step.outputs.TIMESTAMP }}" > variables/last-updated.txt

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "GW | Latest update timestamp"
          file_pattern: variables/last-updated.txt
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
